### ISSUE TITLE
软件无法运行

### ISSUE THREAD

**Issue by z666pr** [Keytoyze/Sword_emulator#1]
win10 Edu1803，Java8。双击后无响应。

**Comment by Keytoyze** [comment]
试一试能不能直接运行jar包（https://github.com/Keytoyze/Sword_emulator/releases/download/v1.0/ZJUQS-II.SWORD.Emulator.jar ）。如果还是没有响应，使用命令java -jar [jar文件路径]查看是否有报错信息。

**Comment by z666pr** [comment]
无法直接运行jar包（无响应），命令java -jar提示WARNING: Loading FXML document with JavaFX API of version 8.0.211 by JavaFX runtime of version 8.0.201
java更新后还是直接运行无响应TAT

**Comment by Keytoyze** [comment]
佛了，试试用命令 java -Dglass.accessible.force=false -jar [jar文件路径]
