### ISSUE TITLE
Mac 下 jar 包报错：找不到或无法加载主类 indi.key.mipsemulator.Main

### ISSUE THREAD

**Issue by shenmishajing** [Keytoyze/Sword_emulator#2]
系统环境：

Mac os Mojave 10.14.5

Java 版本：

> openjdk version "12" 2019-03-19
> OpenJDK Runtime Environment (build 12+33)
> OpenJDK 64-Bit Server VM (build 12+33, mixed mode, sharing)

如下命令：

```
java -jar ZJUQS-II.SWORD.Emulator.jar
java -Dglass.accessible.force=false -jar ZJUQS-II.SWORD.Emulator.jar 
```
均有如下报错：

> 错误: 找不到或无法加载主类 indi.key.mipsemulator.Main
> 原因: java.lang.NoClassDefFoundError: javafx/application/Application

求问如何运行 jar 包或者编译源代码
qwq

**Comment by Keytoyze** [comment]
似乎是JDK12移除了JavaFX，所以只能自己加上了
https://github.com/Keytoyze/Sword_emulator/releases 试试v1.0.1-alpha能不能运行？

**Comment by shenmishajing** [comment]
v1.0.1-alpha版本还是会报如上的错误……

**Comment by Keytoyze** [comment]
参考一下https://stackoverflow.com/questions/53533486/how-to-open-javafx-jar-file-with-jdk-11 的方法，去https://openjfx.io/ 下载一下对应平台的jar模块，然后用java --module-path [sdk目录] --add-modules javafx.controls,javafx.fxml -jar [jar文件路径]看看能不能运行

**Comment by zouyonghao** [comment]
@Keytoyze 建议用```maven```构建工程，使用```zenjava```的插件打native包

https://github.com/javafx-maven-plugin/javafx-maven-plugin

**Comment by Keytoyze** [comment]
@zouyonghao 感谢！

**Comment by Keytoyze** [comment]
Fix with zenjava
