### ISSUE TITLE
单步调试MCPU.coe文件出错

### ISSUE THREAD

**Issue by ziyue-pan** [Keytoyze/Sword_emulator#3]
单步调试MCPU.coe文件时会卡在某些指令死循环，正常运行没有问题。

平台：win10
JRE: 1.8.0_251

[MCPU.coe.txt](https://github.com/Keytoyze/Sword_emulator/files/4733402/MCPU.coe.txt)

去掉.txt扩展名

![bug](https://user-images.githubusercontent.com/50222787/83826655-f8933880-a70e-11ea-855d-e2e46f15e15e.gif)

**Comment by Keytoyze** [comment]
这个程序有没有用到计数器？计数器只在运行时候才会起效，单步运行的时候是不计时的

**Comment by ziyue-pan** [comment]
> 这个程序有没有用到计数器？计数器只在运行时候才会起效，单步运行的时候是不计时的

应该没用到。不过我在物理测试的时候出现了和模拟器同样的情况。单步调试时会卡在PC为100到108的指令，自动执行就没问题

**Comment by Keytoyze** [comment]
> > 这个程序有没有用到计数器？计数器只在运行时候才会起效，单步运行的时候是不计时的
> 
> 应该没用到。不过我在物理测试的时候出现了和模拟器同样的情况。单步调试时会卡在PC为100到108的指令，自动执行就没问题

刚才看了一下代码，似乎是读GPIO的，GPIO有个位会标志计数器是否归零，如果单步调试的话计数器可能会有问题

**Comment by ziyue-pan** [comment]
> > > 这个程序有没有用到计数器？计数器只在运行时候才会起效，单步运行的时候是不计时的
> > 
> > 
> > 应该没用到。不过我在物理测试的时候出现了和模拟器同样的情况。单步调试时会卡在PC为100到108的指令，自动执行就没问题
> 
> 刚才看了一下代码，似乎是读GPIO的，GPIO有个位会标志计数器是否归零，如果单步调试的话计数器可能会有问题

ok，十分感谢，看起来模拟器没有问题，应该是测试程序不支持单步调试
