### ISSUE TITLE
文本模式8*8西文下半屏幕无显示

### ISSUE THREAD

**Issue by Luke-Skycrawler** [Keytoyze/Sword_emulator#5]
**[v1.2.4-alpha1已解决]**外设地址为默认值0x000c0000
![image](https://user-images.githubusercontent.com/50949025/84148514-b4e35a80-aa91-11ea-90e0-377137d81ca7.png)

**Comment by Keytoyze** [comment]
提供下coe吧

**Comment by Luke-Skycrawler** [comment]
(source code)
[cls.txt](https://github.com/Keytoyze/Sword_emulator/files/4765747/cls.txt)


`

**Comment by Keytoyze** [comment]
> (source code)
> [cls.txt](https://github.com/Keytoyze/Sword_emulator/files/4765747/cls.txt)
> 
> `

试一下 https://github.com/Keytoyze/Sword_emulator/releases/tag/v1.2.4-alpha1 ，看看有没有问题

**Comment by Luke-Skycrawler** [comment]
已解决
(star+1)

**Comment by Keytoyze** [comment]
稳
