### ISSUE TITLE
模拟器图形模式放置像素点时会在右侧放置一个黑色像素点?

### ISSUE THREAD

**Issue by LahElr** [Keytoyze/Sword_emulator#6]
<img src="https://user-images.githubusercontent.com/61791673/85145708-921a2880-b27f-11ea-870e-3f034069bb1e.png" alt="new" style="zoom:700%;" />

新版模拟器会出现这样的情况，推断是为了解决旧模拟器一个模拟器像素点由横向两个现实屏幕像素点组成的问题而在输出一个模拟器像素点时在右边放置了一个黑色现实像素点的缘故。
这一问题会导致当用户自右向左输出一行像素点时只能看到最后一个像素点。
这是旧版模拟器的输出：

<img src="https://user-images.githubusercontent.com/61791673/85145769-a9f1ac80-b27f-11ea-9891-d84348d43432.png" alt="old" style="zoom:700%;" />

**Comment by Keytoyze** [comment]
你在“查看内存”里面检查一下对应的VRAM地址区域，数据排列是否是正确的？一个像素点占2 bytes，所以如果使用sw来直接储存一个像素点，是会导致有一部分0被填充进VRAM的。

**Comment by Keytoyze** [comment]
> ![new](https://user-images.githubusercontent.com/61791673/85145708-921a2880-b27f-11ea-870e-3f034069bb1e.png)
> 
> 新版模拟器会出现这样的情况，推断是为了解决旧模拟器一个模拟器像素点由横向两个现实屏幕像素点组成的问题而在输出一个模拟器像素点时在右边放置了一个黑色现实像素点的缘故。
> 这一问题会导致当用户自右向左输出一行像素点时只能看到最后一个像素点。
> 这是旧版模拟器的输出：
> 
> ![old](https://user-images.githubusercontent.com/61791673/85145769-a9f1ac80-b27f-11ea-9891-d84348d43432.png)

之前旧版的模拟器bug，是会导致重复绘制（也就是如果使用sw来储存一个像素点，低位有效的颜色值会被重复填充至两个像素点，高位的0被无视了）。你可以尝试使用sw一次性储存两个像素点的值，或者使用sh指令。

**Comment by LahElr** [comment]
是这个样子的，试验了确实如此。谢谢学长大半夜答疑。
